/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as DashboardCreateStrategyRouteImport } from "./app/dashboard/create-strategy";
import { Route as DashboardIndexRouteImport } from "./app/dashboard/index";
import { Route as DashboardMintRouteImport } from "./app/dashboard/mint";
import { Route as DashboardRouteRouteImport } from "./app/dashboard/route";
import { Route as DashboardSettingsRouteImport } from "./app/dashboard/settings";
import { Route as DashboardWrapRouteImport } from "./app/dashboard/wrap";
import { Route as IndexRouteImport } from "./app/index";

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/dashboard",
  path: "/dashboard",
} as any);
const IndexRoute = IndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/",
  path: "/",
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/",
  path: "/",
} as any);
const DashboardWrapRoute = DashboardWrapRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/wrap",
  path: "/wrap",
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/settings",
  path: "/settings",
} as any);
const DashboardMintRoute = DashboardMintRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/mint",
  path: "/mint",
} as any);
const DashboardCreateStrategyRoute = DashboardCreateStrategyRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/create-strategy",
  path: "/create-strategy",
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/dashboard/create-strategy": typeof DashboardCreateStrategyRoute;
  "/dashboard/mint": typeof DashboardMintRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/wrap": typeof DashboardWrapRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard/create-strategy": typeof DashboardCreateStrategyRoute;
  "/dashboard/mint": typeof DashboardMintRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/wrap": typeof DashboardWrapRoute;
  "/dashboard": typeof DashboardIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/dashboard/create-strategy": typeof DashboardCreateStrategyRoute;
  "/dashboard/mint": typeof DashboardMintRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/wrap": typeof DashboardWrapRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/dashboard/create-strategy"
    | "/dashboard/mint"
    | "/dashboard/settings"
    | "/dashboard/wrap"
    | "/dashboard/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard/create-strategy"
    | "/dashboard/mint"
    | "/dashboard/settings"
    | "/dashboard/wrap"
    | "/dashboard";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/dashboard/create-strategy"
    | "/dashboard/mint"
    | "/dashboard/settings"
    | "/dashboard/wrap"
    | "/dashboard/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/wrap": {
      id: "/dashboard/wrap";
      path: "/wrap";
      fullPath: "/dashboard/wrap";
      preLoaderRoute: typeof DashboardWrapRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/mint": {
      id: "/dashboard/mint";
      path: "/mint";
      fullPath: "/dashboard/mint";
      preLoaderRoute: typeof DashboardMintRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/create-strategy": {
      id: "/dashboard/create-strategy";
      path: "/create-strategy";
      fullPath: "/dashboard/create-strategy";
      preLoaderRoute: typeof DashboardCreateStrategyRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardCreateStrategyRoute: typeof DashboardCreateStrategyRoute;
  DashboardMintRoute: typeof DashboardMintRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardWrapRoute: typeof DashboardWrapRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCreateStrategyRoute: DashboardCreateStrategyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMintRoute: DashboardMintRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWrapRoute: DashboardWrapRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  IndexRoute: IndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
